name: comunikt
description: Instant messaging application implemented using Flutter and Supabase services.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  beamer: ^0.13.3
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  device_preview: ^0.7.1
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_chat_ui: ^1.0.5
  formz: ^0.4.0
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  hive: ^2.0.4
  injectable: ^1.4.1
  json_annotation: ^4.0.1
  logger: ^1.0.0
  path_provider: ^2.0.1
  responsive_builder: ^0.4.1
  supabase: ^0.0.1-dev.16

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.2
  lint: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
