name: comunikt
description: Instant messaging application implemented using Flutter and Supabase services.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  cupertino_icons: ^1.0.3
  device_preview: ^0.7.1
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^0.14.2
  get: ^4.1.4
  get_it: ^7.1.3
  json_annotation: ^4.0.1
  logger: ^1.0.0
  shared_preferences: ^2.0.5
  supabase: ^0.0.1-dev.16

dev_dependencies:
  build_runner: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  json_serializable: ^4.1.2
  lint: ^1.5.3

flutter:
  uses-material-design: true
